Make sure logging functions always receive correct value

diff --git a/bin/mysqldump-secure b/bin/mysqldump-secure
--- a/bin/mysqldump-secure
+++ b/bin/mysqldump-secure
@@ -62,7 +62,7 @@ _DEFAULT_DUMP_PATH="${_PREFIX_ETC}/var/mysqldump-secure"
 
 # MySQL defaults
 _DEFAULT_MYSQL_CNF_CHMOD="0400"
-_DEFAULT_MYSQL_CNF_FILE="${_PREFIX_ETC}/etc/mysqldump-secure.cnf"
+#_DEFAULT_MYSQL_CNF_FILE="${_PREFIX_ETC}/etc/mysqldump-secure.cnf"
 
 
 # Default OpenSSL Variables
@@ -141,7 +141,13 @@ debug() {
 		# Show debug output?
 		if [ "${_debug}" = "1" ]; then
 			[ "${_lvl}" = "verbose" ] && printf "${CLR_DEBUG}[DEBUG] %s\n${CLR_RESET}" "${_msg}"
+		elif [ "${_debug}" != "0" ]; then
+			echo "Invalid value for \$_debug"
+			exit 1
 		fi
+	elif [ "${_cron}" != "0" ]; then
+		echo "Invalid value for \$_cron"
+		exit 1
 	fi
 
 
@@ -157,7 +163,11 @@ debug() {
 		[ "${_lvl}" = "warn" ]  && _pre="[WARN] "
 		[ "${_lvl}" = "err" ]   && _pre="[ERR]  "
 		printf "%s %s %s %s\n" "$(date '+%Y-%m-%d')" "$(date '+%H:%M:%S')" "${_pre}" "${_msg}" >> "${_file}"
+	elif [ "${_log}" != "0" ]; then
+		echo "Invalid value for \$_log"
+		exit 1
 	fi
+
 	return 0
 }
 
@@ -201,7 +211,13 @@ debugr() {
 				done
 				unset IFS
 			fi
+		elif [ "${_debug}" != "0" ]; then
+			echo "Invalid value for \$_debug"
+			exit 1
 		fi
+	elif [ "${_cron}" != "0" ]; then
+		echo "Invalid value for \$_cron"
+		exit 1
 	fi
 
 
@@ -240,7 +256,11 @@ debugr() {
 			printf "%s %s %s %s\n" "$(date '+%Y-%m-%d')" "$(date '+%H:%M:%S')" "${_pre}" "${line}" >> "${_file}"
 		done
 		unset IFS
+	elif [ "${_log}" != "0" ]; then
+		echo "Invalid value for \$_log"
+		exit 1
 	fi
+
 	return 0
 }
 
@@ -269,7 +289,13 @@ debugi() {
 		# Show debug output?
 		if [ "${_debug}" = "1" ]; then
 			[ "${_lvl}" = "verbose" ] && printf "${CLR_DEBUG}[DEBUG] %s${CLR_RESET}" "${_msg}"
+		elif [ "${_debug}" != "0" ]; then
+			echo "Invalid value for \$_debug"
+			exit 1
 		fi
+	elif [ "${_cron}" != "0" ]; then
+		echo "Invalid value for \$_cron"
+		exit 1
 	fi
 
 
@@ -285,6 +311,9 @@ debugi() {
 		[ "${_lvl}" = "warn" ]  && _pre="[WARN] "
 		[ "${_lvl}" = "err" ]   && _pre="[ERR]  "
 		printf "%s %s %s %s" "$(date '+%Y-%m-%d')" "$(date '+%H:%M:%S')" "${_pre}" "${_msg}" >> "${_file}"
+	elif [ "${_log}" != "0" ]; then
+		echo "Invalid value for \$_log"
+		exit 1
 	fi
 	return 0
 }
@@ -313,7 +342,13 @@ debugn() {
 		# Show debug output?
 		if [ "${_debug}" = "1" ]; then
 			[ "${_lvl}" = "verbose" ] && printf "${CLR_DEBUG}%s\n${CLR_RESET}" "${_msg}"
+		elif [ "${_debug}" != "0" ]; then
+			echo "Invalid value for \$_debug"
+			exit 1
 		fi
+	elif [ "${_cron}" != "0" ]; then
+		echo "Invalid value for \$_cron"
+		exit 1
 	fi
 
 
@@ -322,14 +357,20 @@ debugn() {
 	[ "${_lvl}" = "err"  ] && printf "${CLR_ERROR}%s\n${CLR_RESET}" "${_msg}" 1>&2	# stdout -> stderr
 
 	# Log to file
-	[ "${_log}" = "1"    ] && printf "%s\n" "${_msg}" >> "${_file}"
+	if [ "${_log}" = "1" ]; then
+		printf "%s\n" "${_msg}" >> "${_file}"
+	elif [ "${_log}" != "0" ]; then
+		echo "Invalid value for \$_log"
+		exit 1
+	fi
+
 	return 0
 }
 
 # Output to stdout/stderr and to file (simply output a newline).
 #
 # @param  string  _lvl	Debug Level
-# @param  string  _log	'1': log to file | else: do not log to file
+# @param  string  _log	'1': log to file | 0: do not log to file
 # @param  string  _file	Full path to logfile
 # @param  string  _cron '1': Cron usage - do not print 'info' | else: print all
 # @return integer 0
@@ -346,7 +387,13 @@ debug_nl() {
 		# Show debug output?
 		if [ "${_debug}" = "1" ]; then
 			[ "${_lvl}" = "verbose" ] && printf "\n"
+		elif [ "${_debug}" != "0" ]; then
+			echo "Invalid value for \$_debug"
+			exit 1
 		fi
+	elif [ "${_cron}" != "0" ]; then
+		echo "Invalid value for \$_cron"
+		exit 1
 	fi
 
 	# Always show warn and error
@@ -354,7 +401,13 @@ debug_nl() {
 	[ "${_lvl}" = "err"  ] && printf "\n" 1>&2	# stdout -> stderr
 
 	# Log to file
-	[ "${_log}" = "1"    ] && printf "\n" >> "${_file}"
+	if [ "${_log}" = "1" ]; then
+		printf "\n" >> "${_file}"
+	elif [ "${_log}" != "0" ]; then
+		echo "Invalid value for \$_log"
+		exit 1
+	fi
+
 	return 0
 }
 
@@ -1100,10 +1153,10 @@ if [ "${LOG}" = "1" ]; then
 		echo "--------------------------------------------------------------------------------";
 		echo "$(date '+%Y-%m-%d') $(date '+%H:%M:%S') Starting";
 	} >> "${LOGFILE}"
-	debug "info" "(CFG): Using config: ${CONFIG_FILE}" ${LOG} "${LOGFILE}" "${_ARG_CRON}"
-	debug "info" "(OPT): Logging enabled: ${LOGFILE}" ${LOG} "${LOGFILE}" "${_ARG_CRON}"
+	debug "info" "(CFG): Using config: ${CONFIG_FILE}" $LOG "${LOGFILE}" "${_ARG_CRON}" "${_ARG_VERB}"
+	debug "info" "(OPT): Logging enabled: ${LOGFILE}" $LOG "${LOGFILE}" "${_ARG_CRON}" "${_ARG_VERB}"
 else
-	debug "info" "(CFG): Using config: ${CONFIG_FILE}" ${LOG} "${LOGFILE}" "${_ARG_CRON}"
+	debug "info" "(CFG): Using config: ${CONFIG_FILE}" $LOG "${LOGFILE}" "${_ARG_CRON}" "${_ARG_VERB}"
 fi
 
 
@@ -1112,16 +1165,16 @@ fi
 # Command line arguments
 ############################################################
 if [ "${_ARG_CRON}" = "1" ]; then
-	debug "info" "(ARG): Running in cron mode (--cron)." ${LOG} "${LOGFILE}" "${_ARG_CRON}"
+	debug "info" "(ARG): Running in cron mode (--cron)." $LOG "${LOGFILE}" "${_ARG_CRON}" "${_ARG_VERB}"
 fi
 if [ "${_ARG_TEST}" = "1" ]; then
-	debug "info" "(ARG): Running tests only (--test)." ${LOG} "${LOGFILE}" "${_ARG_CRON}"
+	debug "info" "(ARG): Running tests only (--test)." $LOG "${LOGFILE}" "${_ARG_CRON}" "${_ARG_VERB}"
 fi
 if [ "${_ARG_VERB}" = "1" ]; then
-	debug "info" "(ARG): Running in verbose mode (--verbose)." ${LOG} "${LOGFILE}" "${_ARG_CRON}"
+	debug "info" "(ARG): Running in verbose mode (--verbose)." $LOG "${LOGFILE}" "${_ARG_CRON}" "${_ARG_VERB}"
 fi
 #if [ "${_ARG_INFO}" = "1" ]; then
-#	debug "info" "Showing information only (--info)."  ${LOG} "${LOGFILE}" "${_ARG_CRON}"
+#	debug "info" "Showing information only (--info)."  $LOG "${LOGFILE}" "${_ARG_CRON}" "${_ARG_VERB}"
 #fi
 
 
@@ -1131,105 +1184,105 @@ fi
 
 # Check $DUMP_DIR_CHMOD
 if ! set | grep '^DUMP_DIR_CHMOD=' >/dev/null 2>&1; then
-	debug "warn" "(CFG): \$DUMP_DIR_CHMOD variable is not defined" "" "" "${_ARG_CRON}" "${_ARG_VERB}"
-	debug "warn" "(CFG): Setting default to: ${_DEFAULT_DUMP_DIR_CHMOD}" "" "" "${_ARG_CRON}" "${_ARG_VERB}"
+	debug "warn" "(CFG): \$DUMP_DIR_CHMOD variable is not defined" $LOG "${LOGFILE}" "${_ARG_CRON}" "${_ARG_VERB}"
+	debug "warn" "(CFG): Setting default to: ${_DEFAULT_DUMP_DIR_CHMOD}" $LOG "${LOGFILE}" "${_ARG_CRON}" "${_ARG_VERB}"
 	DUMP_DIR_CHMOD=${_DEFAULT_DUMP_DIR_CHMOD}
 elif [ -z "${DUMP_DIR_CHMOD}" ]; then
-	debug "warn" "(CFG): \$DUMP_DIR_CHMOD variable should not be empty" "" "" "${_ARG_CRON}" "${_ARG_VERB}"
-	debug "warn" "(CFG): Setting default to: ${_DEFAULT_DUMP_DIR_CHMOD}" "" "" "${_ARG_CRON}" "${_ARG_VERB}"
+	debug "warn" "(CFG): \$DUMP_DIR_CHMOD variable should not be empty" $LOG "${LOGFILE}" "${_ARG_CRON}" "${_ARG_VERB}"
+	debug "warn" "(CFG): Setting default to: ${_DEFAULT_DUMP_DIR_CHMOD}" $LOG "${LOGFILE}" "${_ARG_CRON}" "${_ARG_VERB}"
 	DUMP_DIR_CHMOD=${_DEFAULT_DUMP_DIR_CHMOD}
 elif ! valid_chmod "${DUMP_DIR_CHMOD}" > /dev/null 2>&1; then
-	debug "err"  "(CFG): Invalid value for \$DUMP_DIR_CHMOD: ${DUMP_DIR_CHMOD}" "" "" "${_ARG_CRON}" "${_ARG_VERB}"
-	debug "err"  "(CFG): Setting default to: ${_DEFAULT_DUMP_DIR_CHMOD}" "" "" "${_ARG_CRON}" "${_ARG_VERB}"
+	debug "err"  "(CFG): Invalid value for \$DUMP_DIR_CHMOD: ${DUMP_DIR_CHMOD}" $LOG "${LOGFILE}" "${_ARG_CRON}" "${_ARG_VERB}"
+	debug "err"  "(CFG): Setting default to: ${_DEFAULT_DUMP_DIR_CHMOD}" $LOG "${LOGFILE}" "${_ARG_CRON}" "${_ARG_VERB}"
 	DUMP_DIR_CHMOD="${_DEFAULT_DUMP_DIR_CHMOD}"
 fi
 
 # Check $DUMP_FILE_CHMOD
 if ! set | grep '^DUMP_FILE_CHMOD=' >/dev/null 2>&1; then
-	debug "warn" "(CFG): \$DUMP_FILE_CHMOD variable is not defined" "" "" "${_ARG_CRON}" "${_ARG_VERB}"
-	debug "warn" "(CFG): Setting default to: ${_DEFAULT_DUMP_FILE_CHMOD}" "" "" "${_ARG_CRON}" "${_ARG_VERB}"
+	debug "warn" "(CFG): \$DUMP_FILE_CHMOD variable is not defined" $LOG "${LOGFILE}" "${_ARG_CRON}" "${_ARG_VERB}"
+	debug "warn" "(CFG): Setting default to: ${_DEFAULT_DUMP_FILE_CHMOD}" $LOG "${LOGFILE}" "${_ARG_CRON}" "${_ARG_VERB}"
 	DUMP_FILE_CHMOD=${_DEFAULT_DUMP_DIR_CHMOD}
 elif [ -z "${DUMP_FILE_CHMOD}" ]; then
-	debug "warn" "(CFG): \$DUMP_FILE_CHMOD variable should not be empty" "" "" "${_ARG_CRON}" "${_ARG_VERB}"
-	debug "warn" "(CFG): Setting default to: ${_DEFAULT_DUMP_FILE_CHMOD}" "" "" "${_ARG_CRON}" "${_ARG_VERB}"
+	debug "warn" "(CFG): \$DUMP_FILE_CHMOD variable should not be empty" $LOG "${LOGFILE}" "${_ARG_CRON}" "${_ARG_VERB}"
+	debug "warn" "(CFG): Setting default to: ${_DEFAULT_DUMP_FILE_CHMOD}" $LOG "${LOGFILE}" "${_ARG_CRON}" "${_ARG_VERB}"
 	DUMP_FILE_CHMOD=${_DEFAULT_DUMP_DIR_CHMOD}
 elif ! valid_chmod "${DUMP_FILE_CHMOD}" > /dev/null 2>&1; then
-	debug "err"  "(CFG): Invalid value for \$DUMP_FILE_CHMOD: ${DUMP_FILE_CHMOD}" "" "" "${_ARG_CRON}" "${_ARG_VERB}"
-	debug "err"  "(CFG): Setting default to: ${_DEFAULT_DUMP_FILE_CHMOD}" "" "" "${_ARG_CRON}" "${_ARG_VERB}"
+	debug "err"  "(CFG): Invalid value for \$DUMP_FILE_CHMOD: ${DUMP_FILE_CHMOD}" $LOG "${LOGFILE}" "${_ARG_CRON}" "${_ARG_VERB}"
+	debug "err"  "(CFG): Setting default to: ${_DEFAULT_DUMP_FILE_CHMOD}" $LOG "${LOGFILE}" "${_ARG_CRON}" "${_ARG_VERB}"
 	DUMP_FILE_CHMOD="${_DEFAULT_DUMP_DIR_CHMOD}"
 fi
 
 # Check $DUMP_PATH
 if ! set | grep '^DUMP_PATH=' >/dev/null 2>&1; then
-	debug "warn" "(CFG): \$DUMP_PATH variable is not defined" "" "" "${_ARG_CRON}" "${_ARG_VERB}"
-	debug "warn" "(CFG): Setting default to: ${_DEFAULT_DUMP_PATH}" "" "" "${_ARG_CRON}" "${_ARG_VERB}"
+	debug "warn" "(CFG): \$DUMP_PATH variable is not defined" $LOG "${LOGFILE}" "${_ARG_CRON}" "${_ARG_VERB}"
+	debug "warn" "(CFG): Setting default to: ${_DEFAULT_DUMP_PATH}" $LOG "${LOGFILE}" "${_ARG_CRON}" "${_ARG_VERB}"
 	DUMP_PATH=${_DEFAULT_DUMP_PATH}
 elif [ -z "${DUMP_PATH}" ]; then
-	debug "warn" "(CFG): \$DUMP_PATH variable should not be empty" "" "" "${_ARG_CRON}" "${_ARG_VERB}"
-	debug "warn" "(CFG): Setting default to: ${_DEFAULT_DUMP_PATH}" "" "" "${_ARG_CRON}" "${_ARG_VERB}"
+	debug "warn" "(CFG): \$DUMP_PATH variable should not be empty" $LOG "${LOGFILE}" "${_ARG_CRON}" "${_ARG_VERB}"
+	debug "warn" "(CFG): Setting default to: ${_DEFAULT_DUMP_PATH}" $LOG "${LOGFILE}" "${_ARG_CRON}" "${_ARG_VERB}"
 	DUMP_PATH=${_DEFAULT_DUMP_PATH}
 fi
 
 # Resolve symlink?
 if [ -L "${DUMP_PATH}" ]; then
 	if _TMP="$(_realpath "${DUMP_PATH}")" >/dev/null 2>&1; then
-		debug "verbose" "(RUN): \$DUMP_PATH is a symlink. Setting target to: ${_TMP}" "" "" "${_ARG_CRON}" "${_ARG_VERB}"
+		debug "verbose" "(RUN): \$DUMP_PATH is a symlink. Setting target to: ${_TMP}" $LOG "${LOGFILE}" "${_ARG_CRON}" "${_ARG_VERB}"
 		DUMP_PATH="${_TMP}"
 	else
-		debug "err"    "(RUN): Cannot resolve symlink of: $DUMP_PATH" "" "" "${_ARG_CRON}" "${_ARG_VERB}"
+		debug "err"    "(RUN): Cannot resolve symlink of: $DUMP_PATH" $LOG "${LOGFILE}" "${_ARG_CRON}" "${_ARG_VERB}"
 		debug "err"    "Aborting"
 		exit 1
 	fi
 fi
 
 if [ ! -d "${DUMP_PATH}" ]; then
-	debug  "warn" "(RUN): Destination dir does not exist: ${DUMP_PATH}" $LOG "${LOGFILE}" "${_ARG_CRON}"
-	debugi "info" "(RUN): Trying to create... " $LOG "${LOGFILE}" "${_ARG_CRON}"
+	debug  "warn" "(RUN): Destination dir does not exist: ${DUMP_PATH}" $LOG "${LOGFILE}" "${_ARG_CRON}" "${_ARG_VERB}"
+	debugi "info" "(RUN): Trying to create... " $LOG "${LOGFILE}" "${_ARG_CRON}" "${_ARG_VERB}"
 	if ! mkdir -p "${DUMP_PATH}" > /dev/null 2>&1 ; then
-		debugn "err"  "Failed" $LOG "${LOGFILE}" "${_ARG_CRON}"
-		debug  "err"  "Aborting" $LOG "${LOGFILE}" "${_ARG_CRON}"
+		debugn "err"  "Failed" $LOG "${LOGFILE}" "${_ARG_CRON}" "${_ARG_VERB}"
+		debug  "err"  "Aborting" $LOG "${LOGFILE}" "${_ARG_CRON}" "${_ARG_VERB}"
 		exit 1
 	else
-		debugn "info" "Done" $LOG "${LOGFILE}" "${_ARG_CRON}"
-		debugi  "info" "(RUN): Trying to chmod to: ${DUMP_DIR_CHMOD}..." $LOG "${LOGFILE}" "${_ARG_CRON}"
+		debugn "info" "Done" $LOG "${LOGFILE}" "${_ARG_CRON}" "${_ARG_VERB}"
+		debugi  "info" "(RUN): Trying to chmod to: ${DUMP_DIR_CHMOD}..." $LOG "${LOGFILE}" "${_ARG_CRON}" "${_ARG_VERB}"
 		if ! chmod ${DUMP_DIR_CHMOD} "${DUMP_PATH}" >/dev/null 2>&1; then
-			debugn "err"  "Failed" $LOG "${LOGFILE}" "${_ARG_CRON}"
-			debug  "err"  "Aborting" $LOG "${LOGFILE}" "${_ARG_CRON}"
+			debugn "err"  "Failed" $LOG "${LOGFILE}" "${_ARG_CRON}" "${_ARG_VERB}"
+			debug  "err"  "Aborting" $LOG "${LOGFILE}" "${_ARG_CRON}" "${_ARG_VERB}"
 			exit 1
 		else
-			debugn "info" "Done" $LOG "${LOGFILE}" "${_ARG_CRON}"
+			debugn "info" "Done" $LOG "${LOGFILE}" "${_ARG_CRON}" "${_ARG_VERB}"
 		fi
 	fi
 fi
 # Check correct permissions of destination dir
 if ! compare_chmod "$(permission "${DUMP_PATH}")" "${DUMP_DIR_CHMOD}" > /dev/null 2>&1 ; then
-	debug  "err"  "(RUN): Target directory has wrong permissions: $(permission "${DUMP_PATH}"), but should ${DUMP_DIR_CHMOD}." $LOG "${LOGFILE}" "${_ARG_CRON}"
-	debugi "info" "(RUN): Trying to chmod to ${DUMP_DIR_CHMOD}... " $LOG "${LOGFILE}" "${_ARG_CRON}"
+	debug  "err"  "(RUN): Target directory has wrong permissions: $(permission "${DUMP_PATH}"), but should ${DUMP_DIR_CHMOD}." $LOG "${LOGFILE}" "${_ARG_CRON}" "${_ARG_VERB}"
+	debugi "info" "(RUN): Trying to chmod to ${DUMP_DIR_CHMOD}... " $LOG "${LOGFILE}" "${_ARG_CRON}" "${_ARG_VERB}"
 
 	if ! chmod "${DUMP_DIR_CHMOD}" "${DUMP_PATH}" > /dev/null 2>&1 ; then
-		debugn "err"  "Failed" $LOG "${LOGFILE}" "${_ARG_CRON}"
-		debug  "err"  "Aborting" $LOG "${LOGFILE}" "${_ARG_CRON}"
+		debugn "err"  "Failed" $LOG "${LOGFILE}" "${_ARG_CRON}" "${_ARG_VERB}"
+		debug  "err"  "Aborting" $LOG "${LOGFILE}" "${_ARG_CRON}" "${_ARG_VERB}"
 		exit 1
 	else
-		debugn "info" "Done" $LOG "${LOGFILE}" "${_ARG_CRON}"
+		debugn "info" "Done" $LOG "${LOGFILE}" "${_ARG_CRON}" "${_ARG_VERB}"
 	fi
 fi
 # Check if destination dir is writeable
 if [ ! -w "${DUMP_PATH}" ]; then
-	debug  "err"  "(RUN): Destination dir ${DUMP_PATH} is not writeable" $LOG "${LOGFILE}" "${_ARG_CRON}"
-	debugi "err"  "(HLP): Fix your configured permissions" $LOG "${LOGFILE}" "${_ARG_CRON}"
-	debug  "err"  "Aborting" $LOG "${LOGFILE}" "${_ARG_CRON}"
+	debug  "err"  "(RUN): Destination dir ${DUMP_PATH} is not writeable" $LOG "${LOGFILE}" "${_ARG_CRON}" "${_ARG_VERB}"
+	debugi "err"  "(HLP): Fix your configured permissions" $LOG "${LOGFILE}" "${_ARG_CRON}" "${_ARG_VERB}"
+	debug  "err"  "Aborting" $LOG "${LOGFILE}" "${_ARG_CRON}" "${_ARG_VERB}"
 	exit 1
 fi
 
 # Check $DUMP_FILE_PRE
 if ! set | grep '^DUMP_FILE_PRE=' >/dev/null 2>&1; then
-	debug "warn" "(CFG): \$DUMP_FILE_PRE variable is not defined" "" "" "${_ARG_CRON}" "${_ARG_VERB}"
-	debug "warn" "(CFG): Setting default to: ${_DEFAULT_DUMP_FILE_PRE}" "" "" "${_ARG_CRON}" "${_ARG_VERB}"
+	debug "warn" "(CFG): \$DUMP_FILE_PRE variable is not defined" $LOG "${LOGFILE}" "${_ARG_CRON}" "${_ARG_VERB}"
+	debug "warn" "(CFG): Setting default to: ${_DEFAULT_DUMP_FILE_PRE}" $LOG "${LOGFILE}" "${_ARG_CRON}" "${_ARG_VERB}"
 	DUMP_FILE_PRE=${_DEFAULT_DUMP_FILE_PRE}
 elif [ -z "${DUMP_FILE_PRE}" ]; then
-	debug "warn" "(CFG): \$DUMP_FILE_PRE variable should not be empty" "" "" "${_ARG_CRON}" "${_ARG_VERB}"
-	debug "warn" "(CFG): Setting default to: ${_DEFAULT_DUMP_FILE_PRE}" "" "" "${_ARG_CRON}" "${_ARG_VERB}"
+	debug "warn" "(CFG): \$DUMP_FILE_PRE variable should not be empty" $LOG "${LOGFILE}" "${_ARG_CRON}" "${_ARG_VERB}"
+	debug "warn" "(CFG): Setting default to: ${_DEFAULT_DUMP_FILE_PRE}" $LOG "${LOGFILE}" "${_ARG_CRON}" "${_ARG_VERB}"
 	DUMP_FILE_PRE=${_DEFAULT_DUMP_FILE_PRE}
 fi
 
@@ -1241,34 +1294,34 @@ fi
 
 # Check Binaries
 if ! command -v mysql > /dev/null 2>&1 ; then
-	debug "err"  "(RUN): 'mysql' not found" $LOG "${LOGFILE}" "${_ARG_CRON}"
-	debug "err"  "Aborting" $LOG "${LOGFILE}" "${_ARG_CRON}"
+	debug "err"  "(RUN): 'mysql' not found" $LOG "${LOGFILE}" "${_ARG_CRON}" "${_ARG_VERB}"
+	debug "err"  "Aborting" $LOG "${LOGFILE}" "${_ARG_CRON}" "${_ARG_VERB}"
 	exit 2
 fi
 if ! command -v mysqldump > /dev/null 2>&1 ; then
-	debug "err"  "(RUN): 'mysqldump' not found" $LOG "${LOGFILE}" "${_ARG_CRON}"
-	debug "err"  "Aborting" $LOG "${LOGFILE}" "${_ARG_CRON}"
+	debug "err"  "(RUN): 'mysqldump' not found" $LOG "${LOGFILE}" "${_ARG_CRON}" "${_ARG_VERB}"
+	debug "err"  "Aborting" $LOG "${LOGFILE}" "${_ARG_CRON}" "${_ARG_VERB}"
 	exit 2
 fi
 
 # Check $MYSQL_CNF_FILE
 if ! set | grep '^MYSQL_CNF_FILE=' >/dev/null 2>&1; then
-	debug "warn" "(CFG): \$MYSQL_CNF_FILE variable is not defined" "" "" "${_ARG_CRON}" "${_ARG_VERB}"
-	debug "warn" "(CFG): Setting default to: ${_DEFAULT_MYSQL_CNF_FILE}" "" "" "${_ARG_CRON}" "${_ARG_VERB}"
-	MYSQL_CNF_FILE=${_DEFAULT_MYSQL_CNF_FILE}
+	debug "err" "(CFG): \$MYSQL_CNF_FILE variable is not defined" $LOG "${LOGFILE}" "${_ARG_CRON}" "${_ARG_VERB}"
+	debug "err" "Aborting" $LOG "${LOGFILE}" "${_ARG_CRON}" "${_ARG_VERB}"
+	exit 1
 elif [ -z "${MYSQL_CNF_FILE}" ]; then
-	debug "warn" "(CFG): \$MYSQL_CNF_FILE variable should not be empty" "" "" "${_ARG_CRON}" "${_ARG_VERB}"
-	debug "warn" "(CFG): Setting default to: ${_DEFAULT_MYSQL_CNF_FILE}" "" "" "${_ARG_CRON}" "${_ARG_VERB}"
-	MYSQL_CNF_FILE=${_DEFAULT_MYSQL_CNF_FILE}
+	debug "err" "(CFG): \$MYSQL_CNF_FILE variable should not be empty" $LOG "${LOGFILE}" "${_ARG_CRON}" "${_ARG_VERB}"
+	debug "err" "Aborting" $LOG "${LOGFILE}" "${_ARG_CRON}" "${_ARG_VERB}"
+	exit 1
 fi
 
 # Resolve symlink?
 if [ -L "${MYSQL_CNF_FILE}" ]; then
 	if _TMP="$(_realpath "${MYSQL_CNF_FILE}")" >/dev/null 2>&1; then
-		debug "verbose" "(RUN): \$MYSQL_CNF_FILE is a symlink. Setting target to: ${_TMP}" "" "" "${_ARG_CRON}" "${_ARG_VERB}"
+		debug "verbose" "(RUN): \$MYSQL_CNF_FILE is a symlink. Setting target to: ${_TMP}" $LOG "${LOGFILE}" "${_ARG_CRON}" "${_ARG_VERB}"
 		MYSQL_CNF_FILE="${_TMP}"
 	else
-		debug "err"    "(RUN): Cannot resolve symlink of: $MYSQL_CNF_FILE" "" "" "${_ARG_CRON}" "${_ARG_VERB}"
+		debug "err"    "(RUN): Cannot resolve symlink of: $MYSQL_CNF_FILE" $LOG "${LOGFILE}" "${_ARG_CRON}" "${_ARG_VERB}"
 		debug "err"    "Aborting"
 		exit 1
 	fi
