Fix: Add exception when db already exists on disk

diff --git a/bin/mysqldump-secure b/bin/mysqldump-secure
--- a/bin/mysqldump-secure
+++ b/bin/mysqldump-secure
@@ -1163,100 +1163,129 @@ for db in ${DATABASES}; do
 
 	if [ ${skip} -eq 0 ]; then
 
-		# Check required databases
-		for req in ${REQUIRE}; do
-			# Required database found?
-			# Remove from variable
-			if [ "${db}" = "${req}" ]; then
-				REQUIRE="$( echo "${REQUIRE}" | sed "s/${db}//" )"
-			fi
-		done
-
-		DB_SIZE="$( ${MYSQL} --defaults-extra-file="${MYSQL_CNF_FILE}" --batch \
-			-e "SELECT SUM(ROUND(((DATA_LENGTH + INDEX_LENGTH ) / 1024 / 1024),2)) AS Size
-				FROM INFORMATION_SCHEMA.TABLES
-				WHERE TABLE_SCHEMA = '${db}';" | tail -n1 )"
-
-		TOTAL_SIZE=$( sum "${TOTAL_SIZE}" "${DB_SIZE}" )
-		starttime=$(date +%s)
-		ext=""	# file extension
-
+		# Get file extension
 		if [ ${COMPRESS} -eq 1 ]; then
 			if [ ${ENCRYPT} -eq 1 ]; then
 				ext=".sql.${COMPRESS_EXT}.enc"
-				debugi "info"  "Dumping:  ${db} (${DB_SIZE} MB) (compressed) (encrypted) " $LOG "${LOGFILE}" "${_ARG_CRON}"
-
-				# execute with POSIX pipestatus emulation (needs to get rid of shellcheck)
-				umask "$(chmod_2_umask "${DUMP_FILE_CHMOD}")";
-				exec 4>&1
-				# shellcheck disable=SC2086
-				error_statuses="$( (
-					(${MYSQLDUMP} --defaults-extra-file="${MYSQL_CNF_FILE}" ${MYSQL_OPTS} "${db}" || echo "0:$?" >&3) |
-					(${COMPRESS_BIN} ${COMPRESS_ARG} || echo "1:$?" >&3) |
-					(${OPENSSL} smime -encrypt -binary -text -outform DER ${OPENSSL_ALGO_ARG} -out "${DUMP_PATH}/${DUMP_FILE_PRE}${db}${ext}" "${OPENSSL_PUBKEY_PEM}" || echo "2:$?" >&3)
-				) 3>&1 >&4)"
-				exec 4>&-
-
 			else
 				ext=".sql.${COMPRESS_EXT}"
-				debugi "info" "Dumping:  ${db} (${DB_SIZE} MB) (compressed) " $LOG "${LOGFILE}" "${_ARG_CRON}"
-
-				# execute with POSIX pipestatus emulation (needs to get rid of shellcheck)
-				umask "$(chmod_2_umask "${DUMP_FILE_CHMOD}")"
-				exec 4>&1
-				# shellcheck disable=SC2086
-				error_statuses="$( (
-					(${MYSQLDUMP} --defaults-extra-file="${MYSQL_CNF_FILE}" ${MYSQL_OPTS} "${db}" || echo "0:$?" >&3) |
-					(${COMPRESS_BIN} ${COMPRESS_ARG} > "${DUMP_PATH}/${DUMP_FILE_PRE}${db}${ext}" || echo "1:$?" >&3)
-				) 3>&1 >&4)"
-				exec 4>&-
-
 			fi
 		else
 			if [ ${ENCRYPT} -eq 1 ]; then
 				ext=".sql.enc"
-				debugi "info" "Dumping:  ${db} (${DB_SIZE} MB) (encrypted) " $LOG "${LOGFILE}" "${_ARG_CRON}"
-
-				# execute with POSIX pipestatus emulation (needs to get rid of shellcheck)
-				umask "$(chmod_2_umask "${DUMP_FILE_CHMOD}")";
-				exec 4>&1
-				# shellcheck disable=SC2086
-				error_statuses="$( (
-					(${MYSQLDUMP} --defaults-extra-file="${MYSQL_CNF_FILE}" ${MYSQL_OPTS} "${db}" || echo "0:$?" >&3) |
-					(${OPENSSL} smime -encrypt -binary -text -outform DER ${OPENSSL_ALGO_ARG} -out "${DUMP_PATH}/${DUMP_FILE_PRE}${db}${ext}" "${OPENSSL_PUBKEY_PEM}" || echo "1:$?" >&3)
-				) 3>&1 >&4)"
-				exec 4>&-
-
 			else
 				ext=".sql"
-				debugi "info" "Dumping:  ${db} (${DB_SIZE} MB) " $LOG "${LOGFILE}" "${_ARG_CRON}"
-
-				# execute with POSIX pipestatus emulation (needs to get rid of shellcheck)
-				umask "$(chmod_2_umask "${DUMP_FILE_CHMOD}")";
-				exec 4>&1
-				# shellcheck disable=SC2086
-				error_statuses="$( (
-					(${MYSQLDUMP} --defaults-extra-file="${MYSQL_CNF_FILE}" ${MYSQL_OPTS} "${db}" > "${DUMP_PATH}/${DUMP_FILE_PRE}${db}${ext}" || echo "0:$?" >&3)
-				) 3>&1 >&4)"
-				exec 4>&-
-
 			fi
 		fi
 
-		TOTAL_DBS=$((TOTAL_DBS + 1))
 
+		# File already exists on disk?
+		if [ -f "${DUMP_PATH}/${DUMP_FILE_PRE}${db}${ext}" ]; then
 
-		# No errors in POSIX pipestatus emulation
-		if [ -z "$error_statuses" ]; then
-			endtime=$(date +%s)
-			debugn "info" "$((endtime - starttime)) sec" $LOG "${LOGFILE}" "${_ARG_CRON}"
+			# Add failed db to nagios log
+			[ "${NAGIOS_DB_ERROR}" = "" ] && NAGIOS_DB_ERROR="${db}" || NAGIOS_DB_ERROR="${NAGIOS_DB_ERROR},${db}"
 
-			[ "${NAGIOS_DB_DUMPED}" = "" ] && NAGIOS_DB_DUMPED="${db}" || NAGIOS_DB_DUMPED="${NAGIOS_DB_DUMPED},${db}"
-		else
-			debugn "err"  "ERROR" $LOG "${LOGFILE}" "${_ARG_CRON}"
+			debugn "err"  "ERROR:    ${db} cannot be written to disk (file exists: ${DUMP_PATH}/${DUMP_FILE_PRE}${db}${ext})" $LOG "${LOGFILE}" "${_ARG_CRON}"
 			ERROR=1
 
-			[ "${NAGIOS_DB_ERROR}" = "" ] && NAGIOS_DB_ERROR="${db}" || NAGIOS_DB_ERROR="${NAGIOS_DB_ERROR},${db}"
+		# All Good, file can be written
+		else
+
+			# Check required databases
+			for req in ${REQUIRE}; do
+				# Required database found?
+				# Remove from variable
+				if [ "${db}" = "${req}" ]; then
+					REQUIRE="$( echo "${REQUIRE}" | sed "s/${db}//" )"
+				fi
+			done
+
+			DB_SIZE="$( ${MYSQL} --defaults-extra-file="${MYSQL_CNF_FILE}" --batch \
+				-e "SELECT SUM(ROUND(((DATA_LENGTH + INDEX_LENGTH ) / 1024 / 1024),2)) AS Size
+					FROM INFORMATION_SCHEMA.TABLES
+					WHERE TABLE_SCHEMA = '${db}';" | tail -n1 )"
+
+			TOTAL_SIZE=$( sum "${TOTAL_SIZE}" "${DB_SIZE}" )
+			starttime=$(date +%s)
+
+			if [ ${COMPRESS} -eq 1 ]; then
+				if [ ${ENCRYPT} -eq 1 ]; then
+					ext=".sql.${COMPRESS_EXT}.enc"
+					debugi "info"  "Dumping:  ${db} (${DB_SIZE} MB) (compressed) (encrypted) " $LOG "${LOGFILE}" "${_ARG_CRON}"
+
+					# execute with POSIX pipestatus emulation (needs to get rid of shellcheck)
+					umask "$(chmod_2_umask "${DUMP_FILE_CHMOD}")";
+					exec 4>&1
+					# shellcheck disable=SC2086
+					error_statuses="$( (
+						(${MYSQLDUMP} --defaults-extra-file="${MYSQL_CNF_FILE}" ${MYSQL_OPTS} "${db}" || echo "0:$?" >&3) |
+						(${COMPRESS_BIN} ${COMPRESS_ARG} || echo "1:$?" >&3) |
+						(${OPENSSL} smime -encrypt -binary -text -outform DER ${OPENSSL_ALGO_ARG} -out "${DUMP_PATH}/${DUMP_FILE_PRE}${db}${ext}" "${OPENSSL_PUBKEY_PEM}" || echo "2:$?" >&3)
+					) 3>&1 >&4)"
+					exec 4>&-
+
+				else
+					ext=".sql.${COMPRESS_EXT}"
+					debugi "info" "Dumping:  ${db} (${DB_SIZE} MB) (compressed) " $LOG "${LOGFILE}" "${_ARG_CRON}"
+
+					# execute with POSIX pipestatus emulation (needs to get rid of shellcheck)
+					umask "$(chmod_2_umask "${DUMP_FILE_CHMOD}")"
+					exec 4>&1
+					# shellcheck disable=SC2086
+					error_statuses="$( (
+						(${MYSQLDUMP} --defaults-extra-file="${MYSQL_CNF_FILE}" ${MYSQL_OPTS} "${db}" || echo "0:$?" >&3) |
+						(${COMPRESS_BIN} ${COMPRESS_ARG} > "${DUMP_PATH}/${DUMP_FILE_PRE}${db}${ext}" || echo "1:$?" >&3)
+					) 3>&1 >&4)"
+					exec 4>&-
+
+				fi
+			else
+				if [ ${ENCRYPT} -eq 1 ]; then
+					ext=".sql.enc"
+					debugi "info" "Dumping:  ${db} (${DB_SIZE} MB) (encrypted) " $LOG "${LOGFILE}" "${_ARG_CRON}"
+
+					# execute with POSIX pipestatus emulation (needs to get rid of shellcheck)
+					umask "$(chmod_2_umask "${DUMP_FILE_CHMOD}")";
+					exec 4>&1
+					# shellcheck disable=SC2086
+					error_statuses="$( (
+						(${MYSQLDUMP} --defaults-extra-file="${MYSQL_CNF_FILE}" ${MYSQL_OPTS} "${db}" || echo "0:$?" >&3) |
+						(${OPENSSL} smime -encrypt -binary -text -outform DER ${OPENSSL_ALGO_ARG} -out "${DUMP_PATH}/${DUMP_FILE_PRE}${db}${ext}" "${OPENSSL_PUBKEY_PEM}" || echo "1:$?" >&3)
+					) 3>&1 >&4)"
+					exec 4>&-
+
+				else
+					ext=".sql"
+					debugi "info" "Dumping:  ${db} (${DB_SIZE} MB) " $LOG "${LOGFILE}" "${_ARG_CRON}"
+
+					# execute with POSIX pipestatus emulation (needs to get rid of shellcheck)
+					umask "$(chmod_2_umask "${DUMP_FILE_CHMOD}")";
+					exec 4>&1
+					# shellcheck disable=SC2086
+					error_statuses="$( (
+						(${MYSQLDUMP} --defaults-extra-file="${MYSQL_CNF_FILE}" ${MYSQL_OPTS} "${db}" > "${DUMP_PATH}/${DUMP_FILE_PRE}${db}${ext}" || echo "0:$?" >&3)
+					) 3>&1 >&4)"
+					exec 4>&-
+
+				fi
+			fi
+
+			TOTAL_DBS=$((TOTAL_DBS + 1))
+
+
+			# No errors in POSIX pipestatus emulation
+			if [ -z "$error_statuses" ]; then
+				endtime=$(date +%s)
+				debugn "info" "$((endtime - starttime)) sec" $LOG "${LOGFILE}" "${_ARG_CRON}"
+
+				[ "${NAGIOS_DB_DUMPED}" = "" ] && NAGIOS_DB_DUMPED="${db}" || NAGIOS_DB_DUMPED="${NAGIOS_DB_DUMPED},${db}"
+			else
+				debugn "err"  "ERROR" $LOG "${LOGFILE}" "${_ARG_CRON}"
+				ERROR=1
+
+				[ "${NAGIOS_DB_ERROR}" = "" ] && NAGIOS_DB_ERROR="${db}" || NAGIOS_DB_ERROR="${NAGIOS_DB_ERROR},${db}"
+			fi
+
 		fi
 
 	elif [ ${skip} -eq 1 ]; then
