Testing better error catching (stderr)

diff --git a/bin/mysqldump-secure b/bin/mysqldump-secure
--- a/bin/mysqldump-secure
+++ b/bin/mysqldump-secure
@@ -273,6 +273,34 @@ debugn() {
 	return 0
 }
 
+# Output to stdout/stderr and to file (simply output a newline).
+#
+# @param  string  _lvl	Debug Level
+# @param  string  _log	'1': log to file | else: do not log to file
+# @param  string  _file	Full path to logfile
+# @param  string  _cron '1': Cron usage - do not print 'info' | else: print all
+# @return integer 0
+debug_nl() {
+	_lvl="${1}"		# Loglevel: "info", "warn" or "err"
+	_log="${2}"		# log to file?
+	_file="${3}"	# full path to logfile
+	_cron="${4}"	# run for cron?
+
+	# Hide info output when in cron-mode
+	if [ "${_cron}" != "1" ]; then
+		[ "${_lvl}" = "info" ] && printf "\n"
+	fi
+
+	# Always show warn and error
+	[ "${_lvl}" = "warn" ] && printf "\n" 1>&2	# stdout -> stderr
+	[ "${_lvl}" = "err"  ] && printf "\n" 1>&2	# stdout -> stderr
+
+	# Log to file
+	[ "${_log}" = "1"    ] && printf "\n" >> "${_file}"
+	return 0
+}
+
+
 
 
 ############################################################
@@ -1451,6 +1479,16 @@ ERROR=0
 
 
 ############################################################
+# Create tmp files and folders
+############################################################
+MY_TMP_DIR="$( mktemp -d /tmp/mysqldump-secure.XXXXXXXXXX )"
+MY_TMP_FILE_DUMP="$( mktemp "${MY_TMP_DIR}/.XXXXXXXXXXXXXXX" )"
+MY_TMP_FILE_COMP="$( mktemp "${MY_TMP_DIR}/.XXXXXXXXXXXXXXX" )"
+MY_TMP_FILE_ENCR="$( mktemp "${MY_TMP_DIR}/.XXXXXXXXXXXXXXX" )"
+
+
+
+############################################################
 # Get all databases
 ############################################################
 
@@ -1556,7 +1594,6 @@ for db in ${DATABASES}; do
 
 			TOTAL_SIZE=$( sum "${TOTAL_SIZE}" "${DB_SIZE}" )
 			starttime=$(date +%s)
-			MYSQLDUMP_CMD=""
 
 			if [ ${COMPRESS} -eq 1 ]; then
 				if [ ${ENCRYPT} -eq 1 ]; then
@@ -1568,12 +1605,11 @@ for db in ${DATABASES}; do
 					exec 4>&1
 					# shellcheck disable=SC2086
 					error_statuses="$( (
-						(${MYSQLDUMP} --defaults-file="${MYSQL_CNF_FILE}" ${MYSQL_SSL_ARGS} ${MYSQL_OPTS} "${db}" || echo "0:$?" >&3) |
-						(${COMPRESS_BIN} ${COMPRESS_ARG} || echo "1:$?" >&3) |
-						(${OPENSSL} smime -encrypt -binary -text -outform DER ${OPENSSL_ALGO_ARG} -out "${DUMP_PATH}/${DUMP_FILE_PRE}${db}${ext}" "${OPENSSL_PUBKEY_PEM}" || echo "2:$?" >&3)
+						(${MYSQLDUMP} --defaults-file="${MYSQL_CNF_FILE}" ${MYSQL_SSL_ARGS} ${MYSQL_OPTS} "${db}" 2> "${MY_TMP_FILE_DUMP}" || echo "0:$?:$(cat "${MY_TMP_FILE_DUMP}")" && echo "0:$?:$(cat "${MY_TMP_FILE_DUMP}")" >&3) |
+						(${COMPRESS_BIN} ${COMPRESS_ARG} 2> "${MY_TMP_FILE_COMP}" || echo "1:$?:$(cat "${MY_TMP_FILE_COMP}")" && echo "1:$?:$(cat "${MY_TMP_FILE_COMP}")" >&3) |
+						(${OPENSSL} smime -encrypt -binary -text -outform DER ${OPENSSL_ALGO_ARG} -out "${DUMP_PATH}/${DUMP_FILE_PRE}${db}${ext}" "${OPENSSL_PUBKEY_PEM}" 2> "${MY_TMP_FILE_ENCR}" || echo "2:$?::$(cat "${MY_TMP_FILE_ENCR}")" && echo "2:$?::$(cat "${MY_TMP_FILE_ENCR}")" >&3)
 					) 3>&1 >&4)"
 					exec 4>&-
-					MYSQLDUMP_CMD="${MYSQLDUMP} --defaults-file=\"${MYSQL_CNF_FILE}\" ${MYSQL_SSL_ARGS} ${MYSQL_OPTS} \"${db}\" | ${COMPRESS_BIN} ${COMPRESS_ARG} | ${OPENSSL} smime -encrypt -binary -text -outform DER ${OPENSSL_ALGO_ARG} -out \"${DUMP_PATH}/${DUMP_FILE_PRE}${db}${ext}\" \"${OPENSSL_PUBKEY_PEM}\""
 
 				else
 					ext=".sql.${COMPRESS_EXT}"
@@ -1584,11 +1620,10 @@ for db in ${DATABASES}; do
 					exec 4>&1
 					# shellcheck disable=SC2086
 					error_statuses="$( (
-						(${MYSQLDUMP} --defaults-file="${MYSQL_CNF_FILE}" ${MYSQL_SSL_ARGS} ${MYSQL_OPTS} "${db}" || echo "0:$?" >&3) |
-						(${COMPRESS_BIN} ${COMPRESS_ARG} > "${DUMP_PATH}/${DUMP_FILE_PRE}${db}${ext}" || echo "1:$?" >&3)
+						(${MYSQLDUMP} --defaults-file="${MYSQL_CNF_FILE}" ${MYSQL_SSL_ARGS} ${MYSQL_OPTS} "${db}" 2> "${MY_TMP_FILE_DUMP}" || echo "0:$?:$(cat "${MY_TMP_FILE_DUMP}")" && echo "0:$?:$(cat "${MY_TMP_FILE_DUMP}")" >&3) |
+						(${COMPRESS_BIN} ${COMPRESS_ARG} 2> "${MY_TMP_FILE_COMP}" > "${DUMP_PATH}/${DUMP_FILE_PRE}${db}${ext}" || echo "1:$?::$(cat "${MY_TMP_FILE_COMP}")" && echo "1:$?::$(cat "${MY_TMP_FILE_COMP}")" >&3)
 					) 3>&1 >&4)"
 					exec 4>&-
-					MYSQLDUMP_CMD="${MYSQLDUMP} --defaults-file=\"${MYSQL_CNF_FILE}\" ${MYSQL_SSL_ARGS} ${MYSQL_OPTS} \"${db}\" | ${COMPRESS_BIN} ${COMPRESS_ARG} > \"${DUMP_PATH}/${DUMP_FILE_PRE}${db}${ext}\""
 
 				fi
 			else
@@ -1601,11 +1636,10 @@ for db in ${DATABASES}; do
 					exec 4>&1
 					# shellcheck disable=SC2086
 					error_statuses="$( (
-						(${MYSQLDUMP} --defaults-file="${MYSQL_CNF_FILE}" ${MYSQL_SSL_ARGS} ${MYSQL_OPTS} "${db}" || echo "0:$?" >&3) |
-						(${OPENSSL} smime -encrypt -binary -text -outform DER ${OPENSSL_ALGO_ARG} -out "${DUMP_PATH}/${DUMP_FILE_PRE}${db}${ext}" "${OPENSSL_PUBKEY_PEM}" || echo "1:$?" >&3)
+						(${MYSQLDUMP} --defaults-file="${MYSQL_CNF_FILE}" ${MYSQL_SSL_ARGS} ${MYSQL_OPTS} "${db}" 2> "${MY_TMP_FILE_DUMP}" || echo "0:$?:$(cat "${MY_TMP_FILE_DUMP}")" && echo "0:$?:$(cat "${MY_TMP_FILE_DUMP}")" >&3) |
+						(${OPENSSL} smime -encrypt -binary -text -outform DER ${OPENSSL_ALGO_ARG} -out "${DUMP_PATH}/${DUMP_FILE_PRE}${db}${ext}" "${OPENSSL_PUBKEY_PEM}" 2> "${MY_TMP_FILE_ENCR}" || echo "2:$?::$(cat "${MY_TMP_FILE_ENCR}")" && echo "2:$?::$(cat "${MY_TMP_FILE_ENCR}")" >&3)
 					) 3>&1 >&4)"
 					exec 4>&-
-					MYSQLDUMP_CMD="${MYSQLDUMP} --defaults-file=\"${MYSQL_CNF_FILE}\" ${MYSQL_SSL_ARGS} ${MYSQL_OPTS} \"${db}\" | ${OPENSSL} smime -encrypt -binary -text -outform DER ${OPENSSL_ALGO_ARG} -out \"${DUMP_PATH}/${DUMP_FILE_PRE}${db}${ext}\" \"${OPENSSL_PUBKEY_PEM}\""
 
 				else
 					ext=".sql"
@@ -1616,13 +1650,72 @@ for db in ${DATABASES}; do
 					exec 4>&1
 					# shellcheck disable=SC2086
 					error_statuses="$( (
-						(${MYSQLDUMP} --defaults-file="${MYSQL_CNF_FILE}" ${MYSQL_SSL_ARGS} ${MYSQL_OPTS} "${db}" > "${DUMP_PATH}/${DUMP_FILE_PRE}${db}${ext}" || echo "0:$?" >&3)
+						(${MYSQLDUMP} --defaults-file="${MYSQL_CNF_FILE}" ${MYSQL_SSL_ARGS} ${MYSQL_OPTS} "${db}" 2> "${MY_TMP_FILE_DUMP}" > "${DUMP_PATH}/${DUMP_FILE_PRE}${db}${ext}" || echo "0:$?:$(cat "${MY_TMP_FILE_DUMP}")" && echo "0:$?:$(cat "${MY_TMP_FILE_DUMP}")" >&3)
 					) 3>&1 >&4)"
 					exec 4>&-
-					MYSQLDUMP_CMD="${MYSQLDUMP} --defaults-file=\"${MYSQL_CNF_FILE}\" ${MYSQL_SSL_ARGS} ${MYSQL_OPTS} \"${db}\" > \"${DUMP_PATH}/${DUMP_FILE_PRE}${db}${ext}\""
 
 				fi
 			fi
+
+			# Inside $error_statuses we have the following information.
+			# Note: Not all lines must be there (depends on enabled options)
+			#
+			# "0:<exit code>:<stderr msg>"   <--mysqldump
+			# "1:<exit code>:<stderr msg>"   <--compression
+			# "2:<exit code>:<stderr msg>"   <--openssl
+			#
+			# Cases:
+			#  1. Error code == 0 and <stderr msg> empty      => OK
+			#  2. Error code == 0 and <stderr msg> not empty  => Warning
+			#  3. Error code != 0                             => Error
+
+			MY_ERRORS=""
+			MY_WARNINGS=""
+
+			IFS='
+			'
+			for _err in ${error_statuses}; do
+				_type="$( echo "${_err}" | awk -F ':' '{print $1}' )"
+				_exit="$( echo "${_err}" | awk -F ':' '{print $2}' )"
+				_msg="$(  echo "${_err}" | awk -F ':' '{print $3}' )"
+
+				if [ "${_type}" = "0" ]; then
+					if [ "${_exit}" != "0" ]; then
+						[ -z "${MY_ERRORS}" ] && MY_ERRORS="${_msg}" || MY_ERRORS="${MY_ERRORS}\n${_msg}"
+					elif [ "${_msg}" != "" ]; then
+						[ -z "${MY_WARNINGS}" ] && MY_WARNINGS="${_msg}" || MY_WARNINGS="${MY_WARNINGS}\n${_msg}"
+					fi
+				fi
+
+			done
+			unset IFS
+
+			if [ "${MY_ERRORS}" != "" ]; then
+				TOTAL_ERR=$((TOTAL_ERR + 1))
+				debug_nl "info" $LOG "${LOGFILE}" "${_ARG_CRON}"
+				debug "err" "Error dumping ${db}" $LOG "${LOGFILE}" "${_ARG_CRON}"
+				debug "err" "${MY_ERRORS}" $LOG "${LOGFILE}" "${_ARG_CRON}"
+				ERROR="$(merge_exit_codes "${ERROR}" 2)"
+				[ "${NAGIOS_DB_ERROR}" = "" ] && NAGIOS_DB_ERROR="${db}" || NAGIOS_DB_ERROR="${NAGIOS_DB_ERROR},${db}"
+			fi
+			if [ "${MY_WARNINGS}" != "" ]; then
+				TOTAL_DBS=$((TOTAL_DBS + 1))
+				endtime=$(date +%s)
+				debugn "info" "$((endtime - starttime)) sec" $LOG "${LOGFILE}" "${_ARG_CRON}"
+
+				[ "${NAGIOS_DB_DUMPED}" = "" ] && NAGIOS_DB_DUMPED="${db}" || NAGIOS_DB_DUMPED="${NAGIOS_DB_DUMPED},${db}"
+				debug "warn" "Warning dumping ${db}" $LOG "${LOGFILE}" "${_ARG_CRON}"
+				debug "warn" "${MY_ERRORS}" $LOG "${LOGFILE}" "${_ARG_CRON}"
+			fi
+			# No errors and no warnings
+			if [ "${MY_ERRORS}" = "" ] && [ "${MY_WARNINGS}" = "" ]; then
+				TOTAL_DBS=$((TOTAL_DBS + 1))
+				endtime=$(date +%s)
+				debugn "info" "$((endtime - starttime)) sec" $LOG "${LOGFILE}" "${_ARG_CRON}"
+
+				[ "${NAGIOS_DB_DUMPED}" = "" ] && NAGIOS_DB_DUMPED="${db}" || NAGIOS_DB_DUMPED="${NAGIOS_DB_DUMPED},${db}"
+			fi
+
 
 			# No errors in POSIX pipestatus emulation
 			if [ -z "$error_statuses" ]; then
@@ -1634,8 +1727,9 @@ for db in ${DATABASES}; do
 			else
 				# Increment total dbs error count
 				TOTAL_ERR=$((TOTAL_ERR + 1))
+				debug_nl "info" $LOG "${LOGFILE}" "${_ARG_CRON}"
 				debug "err" "Error dumping ${db}" $LOG "${LOGFILE}" "${_ARG_CRON}"
-				debug "err" "${MYSQLDUMP_CMD}" $LOG "${LOGFILE}" "${_ARG_CRON}"
+				debug "err" "${error_statuses}" $LOG "${LOGFILE}" "${_ARG_CRON}"
 				ERROR="$(merge_exit_codes "${ERROR}" 2)"
 
 				[ "${NAGIOS_DB_ERROR}" = "" ] && NAGIOS_DB_ERROR="${db}" || NAGIOS_DB_ERROR="${NAGIOS_DB_ERROR},${db}"
