Silence errors that are handled by the program itself

diff --git a/.travis/config b/.travis/config
--- a/.travis/config
+++ b/.travis/config
@@ -120,21 +120,36 @@ syn_test() {
 
 	echo "${txtblu}--> Syntax error test:${txtrst}"
 	echo "\$ ${txtblu}${cmd} | grep -E '.*[0-9]*:.*: not found.*'${txtrst}"
-	syntax="$(eval "${cmd} 3>&2 2>&1 1>&3 > /dev/null | grep -E '.*[0-9]*:.*: not found.*'")"
+	unfound="$(eval "${cmd} 3>&2 2>&1 1>&3 > /dev/null | grep -E '.*[0-9]*:.*: not found.*'")"
+	syntax="$(eval "${cmd} 3>&2 2>&1 1>&3 > /dev/null | grep -E '.*[0-9]*:.*: Syntax error:.*'")"
+
 
 	if [ "${syntax}" != "" ]; then
 		echo "${txtpur}===> [FAIL]${txtrst}"
 		echo "${txtpur}===> [FAIL] Syntax error found.${txtrst}"
 		echo "${txtpur}===> [FAIL]${txtrst}"
+		if [ "${unfound}" != "" ]; then
+			echo "${txtpur}${unfound}${txtrst}"
+		fi
 		echo "${txtpur}${syntax}${txtrst}"
 		echo
 		return 1
 	else
-		echo "${txtgrn}===> [OK]${txtrst}"
-		echo "${txtgrn}===> [OK] No Syntax error found.${txtrst}"
-		echo "${txtgrn}===> [OK]${txtrst}"
-		echo
-		return 0
+
+		if [ "${unfound}" != "" ]; then
+			echo "${txtpur}===> [FAIL]${txtrst}"
+			echo "${txtpur}===> [FAIL] Syntax error found.${txtrst}"
+			echo "${txtpur}===> [FAIL]${txtrst}"
+			echo "${txtpur}${unfound}${txtrst}"
+			echo
+			return 1
+		else
+			echo "${txtgrn}===> [OK]${txtrst}"
+			echo "${txtgrn}===> [OK] No Syntax error found.${txtrst}"
+			echo "${txtgrn}===> [OK]${txtrst}"
+			echo
+			return 0
+		fi
 	fi
 }
 
